baseURL = '#'
languageCode = 'gl-es'
title = 'Arco Teo'
theme = 'lightbi-hugo'

enableRobotsTXT = true
enableGitInfo = false
Paginate = 6
summaryLength  = "30"

[params]
mainSections = ["post","posts"]
dateFormat = "02 January 2006"
comments = false

previewCardImagePlacement = "top"
selfHosted = true
readingTime = false
wordCount = false
useHLJS = true
socialShare = true
delayDisqus = true
showRelatedPosts = true
summaryLength  = "9"
lunrSearch = true
gcse = false
lastmod = false
rss = true
pagination = "10"
hideAuthor = false
description="Clube de Tiro con Arco de Teo."

   
[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Avisos"
    url = "/notes/"
    weight = 2

[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3

# [[menu.main]]
#    name = "Collections"
#    url = "/collections/"
#    weight = 4

[[menu.main]]
    name = "Ferramentas"
    url = "https://arco-teo.github.io/ferramentas/"
    weight = 4

[[menu.main]]
    name = "Sobre n√≥s"
    url = "/about/"
    weight = 5


[sitemap]
  changefreq = "weekly"
  priority = 0.7
  filename = "sitemap.xml"
